export interface SocialPost {
  id: string
  brandId: string // New: Associate post with brand
  platform: 'instagram' | 'facebook' | 'tiktok' | 'pinterest' | 'twitter'
  content: string
  media: string[] // URLs from R2
  hashtags: string[]
  scheduledFor?: Date
  publishedAt?: Date
  platformPostId?: string // New: ID from the social platform
  status: 'draft' | 'scheduled' | 'published' | 'failed'
  engagementStats?: {
    likes: number
    comments: number
    shares: number
    views: number
  }
  aiGenerated?: boolean // New: Was this generated by AI
  aiPrompt?: string // New: Custom AI prompt used
  createdAt: Date
  updatedAt: Date
}

export interface BlogPost {
  id: string
  brandId: string // New: Associate blog post with brand
  title: string
  slug: string
  content: string // HTML or Markdown
  excerpt: string
  featuredImage?: string
  author: string
  tags: string[]
  status: 'draft' | 'published' | 'scheduled'
  publishedAt?: Date
  scheduledFor?: Date
  seoTitle?: string
  seoDescription?: string
  views: number
  aiGenerated?: boolean // New: Was this generated by AI
  aiPrompt?: string // New: Custom AI prompt used
  createdAt: Date
  updatedAt: Date
}

export interface EmailCampaign {
  id: string
  name: string
  subject: string
  content: string // HTML
  recipients: number
  status: 'draft' | 'scheduled' | 'sent'
  scheduledFor?: Date
  sentAt?: Date
  stats?: {
    delivered: number
    opened: number
    clicked: number
    unsubscribed: number
  }
  createdAt: Date
  updatedAt: Date
}

export interface ContentCalendarItem {
  id: string
  type: 'social' | 'blog' | 'email'
  title: string
  date: Date
  status: 'planned' | 'in_progress' | 'completed'
  platform?: string
  assignedTo?: string
  notes?: string
}